import{a as b,S as E,i as n}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const w="47281982-63a34c7367b72af3cb7b29a97",L="https://pixabay.com/api/";async function p(t,r,o=15){const l={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o};try{return(await b.get(L,{params:l})).data}catch(e){throw console.error("Error fetching images:",e),e}}const d=document.querySelector(".gallery"),S=new E(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const r=t.map(o=>`<li class="gallery-item">
  <a class="gallery-link" href="${o.largeImageURL}">
    <img
      src="${o.webformatURL}"
      alt="${o.tags}"
    />
    <ul class="img-dscr">
      <li><p><b>Likes</b> ${o.likes}</p></li>
      <li><p><b>Views</b> ${o.views}</p></li>
      <li><p><b>Comments</b> ${o.comments}</p></li>
      <li><p><b>Downloads</b> ${o.downloads}</p></li>
    </ul>
  </a>
</li>`).join("");d.insertAdjacentHTML("beforeend",r),S.refresh()}const v=document.querySelector(".form"),P=document.querySelector("input"),q=document.querySelector(".loader"),g=document.querySelector(".load-btn");let a=1,c="";const m=15;let f=0;function i(t=!1,r=!1){g.hidden=!t,q.hidden=!r}function R(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function y(){a*m>=f&&(i(!1,!1),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"center",timeout:3e3}))}v.addEventListener("submit",async t=>{if(t.preventDefault(),d.innerHTML="",i(!1,!0),c=P.value.trim(),a=1,c==="")return i(!1,!1),n.warning({title:"Caution",message:"Please complete the field!",position:"center",timeout:2e3});try{const r=await p(c,a,m);if(f=r.totalHits,r.hits.length===0)return i(!1,!1),n.info({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"center",timeout:2e3});h(r.hits),i(!0,!1),n.success({title:"Success",message:`Found ${f} images!`,position:"center",timeout:2e3}),y()}catch{i(!1,!1),n.error({title:"Error",message:"There was an error fetching the images.",position:"center",timeout:2e3})}});g.addEventListener("click",async()=>{i(!1,!0),a+=1;try{const t=await p(c,a,m);if(t.hits.length===0)return i(!1,!1),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"center",timeout:3e3});h(t.hits),i(!0,!1),R(),y()}catch{i(!1,!1),n.error({title:"Error",message:"Failed to load more images.",position:"center",timeout:2e3})}});
//# sourceMappingURL=index.js.map
